[pytest]
cache_dir = C:\Temp\pytest_cache
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::pandas.errors.Pandas4Warning
    ignore::DeprecationWarning
addopts = -v --tb=short